name: Nix Flake actions

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    needs: nix-matrix
    strategy:
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix )}}
    runs-on: ${{ matrix.os }}
    name: nix-build ${{ matrix.attr }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo mkdir /nix
          sudo chown "$USER" /nix
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: /nix
      - uses: cachix/install-nix-action@v27
      - run: nix build -L '.#${{ matrix.attr }}'
